# Generated by Django 5.0.6 on 2024-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('executor', 'Исполнитель'), ('reader', 'Читатель')], default='reader', max_length=10),
        ),
    ]
